version: '3.0'

#
# The behavor of this compose can be highly (site) customized by creating 
# a .env file in the root of the project.  see .env.example for an example
#

services:
  api:
    build: './api/.'
    ports: ['0.0.0.0:8000:8000']
    networks: ['alpha-nlu-network']
    # The following (crazy) block is about both:
    # 1) setting default values for app parameteres
    # 2) projecting any changes to those values set in the .env file
    # a line should be added to this list for any env-var/param that the
    # app might need, and its easiest to follow if the var name is kept the
    # same for both the var thats projected into the app (the first name)
    # and the name thats expected in the .env (the second name)
    environment:
      - DOCKER_CONTAINER=${DOCKER_CONTAINER:-YES}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - RASA_URL=${RASA_URL:-http://rasa:5000}
      - DUCKLING_URL=${DUCKLING_URL:-http://haskduck:8000}
      - MODEL_DIR=${MODEL_DIR:-./helpers-stuff/rasa/nlu-model}
    volumes: ["${MODEL_DIR:-./helpers-stuff/rasa/nlu-model}:/app/projects", "${RASA_ER_PIPELINE:-./helpers-stuff/rasa/rasa-er-pipeline.json}:/usr/src/app/rasa-er-pipeline.json"]
    entrypoint: ['node', 'start.js']
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/agent']
  ui:
    build:
      context: './ui/.'
      args:
        - API_URL=${API_URL:-http://localhost:8000} # Needed for running yarn build in Dockerfile
    ports: ['0.0.0.0:3500:3000']
    environment:
      - API_URL=${API_URL:-http://localhost:8000}
    networks: ['alpha-nlu-network']
  rasa:
    image: rasa/rasa_nlu:0.10.4-spacy
    ports: ['0.0.0.0:5000:5000']
    volumes: ["${MODEL_DIR:-./helpers-stuff/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./helpers-stuff/rasa/rasa-config.json}:/app/config.json"]
    networks: ['alpha-nlu-network']
  haskduck:
    image: samtecspg/duckling
    ports: ['0.0.0.0:8500:8000']
    networks: ['alpha-nlu-network']
  redis:
    image: redis:latest
    ports: ['0.0.0.0:6379:6379']
    networks: ['alpha-nlu-network']
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./helpers-stuff/redis-data}:/data

networks: {alpha-nlu-network: {}}
