version: '3.7'

services:
  api:
    build: './api/.'
  ui:
    build:
      context: './ui/.'
      dockerfile: docker/dev.Dockerfile
  rasa:
    build:
      context: './rasa/.'
  duckling:
    build:
      context: './duckling/.'
  redis:
  elasticsearch:
