version: '3.0'
  
services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./local-storage/nginx/nginx.ssl.conf:/etc/nginx/conf.d/default.conf
      - ./local-storage/certbot/conf:/etc/letsencrypt
      - ./local-storage/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./local-storage/certbot/conf:/etc/letsencrypt
      - ./local-storage/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"